### Request param: {"input": "I want to find top-10 books about world history"}
GET http://localhost:8080/chat/simple?input=I%20want%20to%20find%20top-10%20books%20about%20world%20history
Accept: application/json

###

### Use function message with default settings
GET http://localhost:8080/chat/function-message?input=I%20want%20to%20find%20top-10%20books%20about%20world%20history
Accept: application/json

###

### Use function message with changed settings
GET http://localhost:8080/chat/function-message-changed?
    input=I%20want%20to%20find%20top-10%20books%20about%20world%20history
Accept: application/json

###

### Get kernel response using simple prompt
POST http://localhost:8080/kernel/simple
Accept: application/json
Content-Type: application/json

{
  "input": "I want to find top-10 books about world history"
}

###

### Get kernel JSON response
POST http://localhost:8080/kernel/json
Accept: application/json
Content-Type: application/json

{
  "input": "I want to find top-10 books about world history"
}

###
